### ISSUE TITLE
Fatal error: cannot load shared library dllsdlstub

### ISSUE THREAD

**Issue by stu-art** [vog/ocamlsdl-tutorial#1]
Hi, when trying to run your very nice tutorial on Arch Linux using the [ocaml-ocamlsdl 0.9.1-3](aur.archlinux.org/packages/ocaml-ocamlsdl/) package in the AUR, the resulting binary failed at runtime with:

`Fatal error: cannot load shared library dllsdlstub`
`Reason: dllsdlstub.so: cannot open shared object file: No such file or directory`

To fix it, I had to add `/usr/lib/ocaml/sdl` to `/usr/lib/ocaml/ld.conf`.

**Comment by stu-art** [comment]
I'm very new to OCaml, so this maybe well understood by more experienced users.

**Comment by vog** [comment]
From what you describe, this seems to be an issue in Arch Linux. The `ocaml-ocamlsdl` package should take care of setting appropriate paths, not the developer.

Closing this issue for now.

Please report your issue to Arch Linux.
